server:
  port: ${PORT:0}

##HERE, THIS ANOTATION IS USEFUL WHEN WE GOING TO RIBBON
##servicio-productos:
  ##ribbon:
    ##listOfServers: localhost:8080,localhost:8008
#THIS PART IS DOCUMENTED, DUE THAT THE EUREKA AS OF NOW THE MANAGER FOR RIBBON

##Definimos la ubicacion del eureka
eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    enabled: true
    registryFetchIntervalSeconds: 60
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

##Annotations for handling time out
ribbon:
  okToRetryOnAllOperations: true
  ReadTimeout: 500000
  ConnectionTimeout: 500000
  maxAutoRetries: 3
  maxAutoRetriesNextServer: 3

histrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500000